# Script to prepare OS Open Roads Table for pgrouting
# Expects two tables generated by importing the roadlink and roadnode shapefiles
# from the Ordnance Survey Open Roads dataset. It is assumed that the tables are named 'roadlinks'
# and 'roadnodes' and that they are located within a schema named 'openroads'.
# The tables should have an id field consisting of unique integer numbers.
# Roadlinks must be linestring and not multilinestring.
# Gemetry field must be named the_geom.

queries <- readLines("inst/sql/prepare_openroads.sql")
queries <- queries[which(substr(queries, 1, 2)!="--")]
sapply(queries, function(x) dbGetQuery(con,x))

# pgRouting pgr_createVertices requires 2D geometry for roadlinks
# OS Open Roads may have been imported with Z values

query <- paste0("select ST_AsText(the_geom) from openroads.roadlinks limit 1;")
roadlinks_geo_type <- dbGetQuery(con, query)

if (grepl("LINESTRING Z", roadlinks_geo_type, fixed = TRUE) == TRUE) {
  query <- paste0(
    "
    ALTER TABLE openroads.roadlinks
    ALTER COLUMN the_geom TYPE geometry(LineString)
    USING ST_Force2D(the_geom);
    "
  )
}
query <- gsub(pattern = '\\s',
              replacement = " ",
              x = query)
dbGetQuery(con, query)

query <- paste0("select ST_AsText(the_geom) from openroads.roadnodes limit 1;")
roadnodes_geo_type <- dbGetQuery(con, query)

if (grepl("POINT Z", roadnodes_geo_type, fixed = TRUE) == TRUE) {
  query <- paste0(
    "
    ALTER TABLE openroads.roadnodes
    ALTER COLUMN the_geom TYPE geometry(Point)
    USING ST_Force2D(the_geom);
    "
  )
}
query <- gsub(pattern = '\\s',
              replacement = " ",
              x = query)
dbGetQuery(con, query)


# Create pgrouting vertices table

query <- paste0(
  "
  select pgr_createVerticesTable('openroads.roadlinks', 'the_geom', 'source', 'target');
  "
)
query <- gsub(pattern = '\\s',
              replacement = " ",
              x = query)
dbGetQuery(con, query)


# Optional to analyze network
query <- paste0(
  "
  select pgr_analyzegraph('openroads.roadlinks', .001, 'the_geom', 'id', 'source', 'target');
  "
)
query <- gsub(pattern = '\\s',
              replacement = " ",
              x = query)
dbGetQuery(con, query)

